version: '3'
services: 

  postgresdb:
    image: postgres:11.2-alpine
    ports:
    - 5555:5432
    environment:
    - POSTGRES_USER=pavel
    - POSTGRES_PASSWORD=123
    - POSTGRES_DB=postgreCOMP
#    volumes:
#    - ./postgres-data:/var/lib/postgresql/data

  mongo_db:
    image: mongo
    ports:
    - 27019:27017
#    environment:
#    - MONGO_INITDB_ROOT_USERNAME= pavel
#    - MONGO_INITDB_ROOT_PASSWORD= '123'
#    - MONGO_INITDB_DATABASE= mongoCOMP
#    volumes:
#      - ./database:/data/db
  
  pystreamer:
    build: src/
    volumes:
      - ./src:/app
    depends_on:
      - postgresdb
      - mongo_db

  etl:
    build: etl_job/
    volumes:
      - ./etl_job:/etl
    depends_on:
      - postgresdb
      - mongo_db

    